version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      #this will miror the local code into the container
      - ./backend:/app
      # this will make the data presistent
      - backend-data:/app/data
    ports:
      - 4000:4000
    depends_on:
      - mysql
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3001:3000
  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "amir"
      MYSQL_DATABASE: passwordManager
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: "amir"
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: yourDatabase
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
volumes:
  mysql_data:
  mongodb_data:
  backend-data:
  frontend-data:
